export interface Totals {
  asiaImpairmentScale: string;
  injuryComplete: string;
  leftLightTouchTotal: string;
  leftLowerMotorTotal: string;
  leftMotor: string;
  leftMotorTotal: string;
  leftMotorZpp: string;
  leftPinPrickTotal: string;
  leftSensory: string;
  leftSensoryZpp: string;
  leftTouchTotal: string;
  leftUpperMotorTotal: string;
  lowerMotorTotal: string;
  neurologicalLevelOfInjury: string;
  pinPrickTotal: string;
  rightLightTouchTotal: string;
  rightLowerMotorTotal: string;
  rightMotor: string;
  rightMotorTotal: string;
  rightMotorZpp: string;
  rightPinPrickTotal: string;
  rightSensory: string;
  rightSensoryZpp: string;
  rightTouchTotal: string;
  rightUpperMotorTotal: string;
  touchTotal: string;
  upperMotorTotal: string;
}
